server:
  port: 8765
eureka:
  client:
    service-url:
      - defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: test
