server:
  port: ${EXCHANGE_SERVICE_PORT:0}
spring:
  application:
    name: currency-exchange
  #Configuration Server URL
  config:
      import: optional:configserver:http://localhost:8888
  profiles:
      active: test

eureka:
  client:
    # Discovery (Eureka) Service URL
    service-url:
    - defaultZone : http://localhost:8761/eureka