server:
  port: 8181
spring:
  application:
    name: currency-exchange
  config:
      import: optional:configserver:http://localhost:8888
  profiles:
      active: test

eureka:
  client:
    service-url:
    - defaultZone : http://localhost:8761/eureka