resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 5 # in fact, there will be only (5-1=4) retry attempt
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        exponentialMaxWaitDuration: 5s
        retryExceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException
        ignoreExceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
          - io.github.resilience4j.bulkhead.BulkheadFullException
    instances:
      currency-exchange-api-call-retry:
        baseConfig: default

  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 10 #The number of calls after which the error rate is calculated. I have assigned it with a small value for test purpose.
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 1m #Time in which the circuit breaker is to stay in open state before moving to half-open state
        failureRateThreshold: 60 #The Threshold Percentage Above Which the Circuit Breaker will move from Closed to Open State.
        automatic-transition-from-open-to-half-open-enabled: true
        writable-stack-trace-enabled: false
        recordExceptions:
          - java.lang.Throwable
        ignoreExceptions:
          # thrown when a thread pool reaches max threads amount and max queue capacity
          - io.github.resilience4j.bulkhead.BulkheadFullException
    instances:
      currency-exchange-api-call-circuit-breaker:
        baseConfig: default

  thread-pool-bulkhead:
    configs:
      default:
        core-thread-pool-size: 1  # number of processors available-1.
        max-thread-pool-size: 1 # maximum number of processors available. Limit the number of concurrent calls
        keep-alive-duration: 20ms
        queue-capacity: 1
        writable-stack-trace-enabled: true
        context-propagators:
          - com.amsidh.mvc.propagator.MdcContextPropagator
    instances:
      currency-exchange-api-call-bulkhead:
        base-config: default


logging:
  level:
    ROOT: ERROR
    com.amsidh.mvc: info