#@include file-fluent.conf

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |-
    <label @FLUENT_LOG>
      <match fluent.**>
        @type stdout
      </match>
    </label>

    <source>
      @type tail
      path /var/log/containers/currency*.log
      pos_file /var/log/containers/es-containers.log.pos
      tag raw.kubernetes.*
      read_from_head true
      refresh_interval 5s
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key timestamp
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </source>

    # Detect exceptions in the log output and forward them as one log entry.
    <match raw.kubernetes.**>
      @type detect_exceptions
      remove_tag_prefix raw
      message log
      languages java
      stream stream
      multiline_flush_interval 0.1
      max_bytes 500000
      max_lines 1000
    </match>

    # Takes the messages sent over TCP
    <source>
      @type forward
    </source>

    ###### Enriches records with Kubernetes metadata  ######
    <filter kubernetes.**>
     @id filter_kubernetes_metadata_id
     @type kubernetes_metadata
     verify_ssl true
    </filter>

    # Concatenate multi-line logs
    <filter **>
      @type concat
      key log
      multiline_start_regexp /^(\d{4}-\d{1,2}-\d{1,2})/
      separator ""
      timeout_label @processdata
    </filter>

    <label @processdata>
      <match **>
        @type stdout
      </match>
    </label>

    <match kubernetes.var.log.containers.currency**.log>
      @type copy
      <store>
        @type stdout
        output_type json
      </store>
      <store>
        @id copytofile
        @type file
        path /var/log/containers/output
        <format>
          localtime false
        </format>
        <buffer time>
          timekey_wait 1m
          timekey 86400
          timekey_use_utc true
        </buffer>
        <inject>
          localtime false
        </inject>
      </store>
      <store>
        @type elasticsearch
        logstash_format true
        host elasticsearch
        port 9200
      </store>
    </match>
