server:
  port: ${CURRENCY_CONVERSION_SERVICE_PORT:0}
spring:
  application:
    name: currency-conversion
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: test

eureka:
  client:
    service-url:
      - defaultZone: http://localhost:8761/eureka
